[program:uwsgi]
directory = /home/higlass/projects/higlass-server
command = bash -c "mkdir -p /data/log && python manage.py migrate && python manage.py loaddata default-viewconf-fixture.xml; uwsgi --ini /home/higlass/projects/uwsgi.ini --socket :8001 --plugins python --module higlass_server.wsgi --workers $WORKERS"

[program:nginx]
command = /usr/sbin/nginx


[program:ingest_watcher]
command = /bin/bash /ingest_watcher.sh
autostart = true
autorestart = true
startsecs = 1
stderr_logfile = /data/log/ingest_watcher.err.log
stdout_logfile = /data/log/ingest_watcher.out.log

[supervisord]
logfile = /var/log/supervisor/supervisord.log